plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace = 'org.chromium.v8android'

    compileSdk 35

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ["${rootDir}/../build/lib"]
        }
    }

    publishing {
        singleVariant("release")
    }
}

dependencies {}

publishing {
    repositories {
        maven {
            name = 'local'
            url = uri(project.findProperty("distDir") ?: ".")
        }
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release

                groupId = 'org.chromium'
                artifactId = 'v8-android'
                version = project.findProperty("version").replaceAll("\\s", "")

                pom {
                    name = 'v8-android'
                    packaging = 'aar'
                }
            }
        }
    }
}

tasks.register('createAAR') {
    dependsOn 'publishReleasePublicationToLocalRepository'

    def distDir = project.findProperty("distDir")
    def version = project.findProperty("version")

    doFirst {
        if (!distDir) throw new RuntimeException("expecting --project-prop distDir=??? but was empty")
        if (!version) throw new RuntimeException("expecting --project-prop version=??? but was empty")
    }
}
